#!/bin/sh
# postinst script for hello
#
# see: dh_installdeb(1)

echo "============== executing postrm ============="
rm -rf /usr/share/applications/souno-indictor.desktop
rm -rf /usr/bin/appindicator.py
echo "removing hello is ok!"
